[repository]
name = "smartfloat"
authors = ["darko-bunny"]
commit_pins = [
]

[smartfloat]
description = "Toggle floating dengan auto cascade, resize, dan center"
authors = ["darko-bunny"]
output = "smartfloat.so"
build = [
  "make all"
]
